language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
  - pip install coveralls flake8
script:
  - flake8 . --ignore=E501,E402
  - coverage run --source=test_plus setup.py test
after_success:
  - coveralls
env:
  - DJANGO="Django<1.6"
  - DJANGO="Django<1.7"
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"
  - DJANGO="Django<1.11"
  - DJANGO="Django<1.12"
  - DJANGO="Django<2.1"

matrix:
  exclude:
    # Django>=2.0 doesn't support Python 2.7
    - python: "2.7"
      env: DJANGO="Django<2.1"
    # Django>=1.9 doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.11"
    - python: "3.3"
      env: DJANGO="Django<1.12"
    - python: "3.3"
      env: DJANGO="Django<2.1"
    # Django<1.8 doesn't support Python 3.5
    - python: "3.5"
      env: DJANGO="Django<1.6"
    - python: "3.5"
      env: DJANGO="Django<1.7"
    - python: "3.5"
      env: DJANGO="Django<1.8"
    # Django<1.8 doesn't support Python 3.6
    - python: "3.6"
      env: DJANGO="Django<1.6"
    - python: "3.6"
      env: DJANGO="Django<1.7"
    - python: "3.6"
      env: DJANGO="Django<1.8"
